version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:7.0"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
